### ISSUE TITLE
Nothing happens when user clicks 'Start Call' without a webcam

### ISSUE THREAD

**Issue by mslevis** [CS3219-AY2324S1/ay2324s1-course-assessment-g57#34]
### How to Replicate *
1. User A and User B are redirected into collab room after matching
2. User A clicks 'Start Call' without a webcam connected.
3. Button disappears but no video console is displayed. (Nothing happens essentially)

### Current vs Expected behavior *
Following the steps from the previous section, I expected a video interface to appear even though I do not have a webcam connected, but nothing happens instead. 

### Additional Context
This is a high priority because even though webcam may not be connected, users should still be able to use voice chat to communicate if they have a mic connected. People would often opt to use voice chat solely.

**Comment by DanielLimWeiEn** [comment]
https://github.com/AgoraIO-Community/VideoUIKit-Web-React/issues/19

The use of voice only as opposed to webcam + microphone is a known issue with the Agora-React-UIKit and there has been no updates yet to indicate that this feature is coming.

In order to do this, it may require using the agora-web-sdk-ng directly to rewrite the video conferencing component of the application.
